### ISSUE TITLE
Make it a widget

### ISSUE THREAD

**Issue by lfom** [3ddN/Amazfit-Music-Player#1]
Nice app, thanks! Maybe you want to make it a widget (Springboard plugin) using Kieron's example:
https://github.com/KieronQuinn/AmazfitSpringboardPluginExample

If you need help or don't wanna do, I can fork your git and work on it. ;)

**Comment by 3ddN** [comment]
Thank you :) . I took a look at the Springboard repo and it seems to be a bigger project to tranform the app in a widget. At the moment I don't have the time to do it but I think it would be a really great upgrade for the app. If you like to work on it, feel free to do it. I would be happy about that :)

**Comment by lfom** [comment]
I may start to work on it at the end of next month (Octorber). Congrats again, and thanks.

**Comment by tibinet** [comment]
Hello guys, this player is so great, exactly I was looking for for longer time. It will be really great once the widget is created. Cant wait for that :)

**Comment by tibinet** [comment]
Hello, some news about the widget?
Thanks

**Comment by lfom** [comment]
First version: https://github.com/lfom/Amazfit-Music-Player/releases/tag/1.1

**Comment by tibinet** [comment]
Yeeees, this is really good news. I tried it this Saturday during my sport activities and it works very well. 
You mentioned that this is a first version, do you plan some other development?

**Comment by lfom** [comment]
Nope, only fix the bugs that making it a widget were added. Latest version from my fork works fine for me, no more crashes. But some other user complained that some files are not played completely. I have never had such problems, so maybe he has a corrupted file...

https://github.com/lfom/Amazfit-Music-Player/releases/latest
